//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KN_MAX_3.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KN_MAX_3.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dark_purple_oppo_r15_stock {
            get {
                object obj = ResourceManager.GetObject("dark_purple_oppo_r15_stock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD Class.
        /// </summary>
        internal static string ID_STREING_ADD_Class {
            get {
                return ResourceManager.GetString("ID_STREING_ADD_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD Gender.
        /// </summary>
        internal static string ID_STREING_ADD_Gender {
            get {
                return ResourceManager.GetString("ID_STREING_ADD_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD Student.
        /// </summary>
        internal static string ID_STREING_ADD_STU {
            get {
                return ResourceManager.GetString("ID_STREING_ADD_STU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD teacher.
        /// </summary>
        internal static string ID_STREING_ADD_Tech {
            get {
                return ResourceManager.GetString("ID_STREING_ADD_Tech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXIT.
        /// </summary>
        internal static string ID_STREING_EXIT {
            get {
                return ResourceManager.GetString("ID_STREING_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Picsart_25_05_17_21_25_24_132 {
            get {
                object obj = ResourceManager.GetObject("Picsart_25-05-17_21-25-24-132", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Picsart_25_05_17_21_26_18_371___Copy {
            get {
                object obj = ResourceManager.GetObject("Picsart_25-05-17_21-26-18-371 - Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Picsart_25_05_17_21_26_48_522 {
            get {
                object obj = ResourceManager.GetObject("Picsart_25-05-17_21-26-48-522", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Picsart_25_05_17_21_27_00_045___Copy {
            get {
                object obj = ResourceManager.GetObject("Picsart_25-05-17_21-27-00-045 - Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Picsart_25_05_17_21_27_21_083 {
            get {
                object obj = ResourceManager.GetObject("Picsart_25-05-17_21-27-21-083", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Picsart_25_05_17_21_27_45_063 {
            get {
                object obj = ResourceManager.GetObject("Picsart_25-05-17_21-27-45-063", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Picsart_25_05_17_22_21_03_418 {
            get {
                object obj = ResourceManager.GetObject("Picsart_25-05-17_22-21-03-418", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap toppng_com_blue_button_icon_icon_845x845 {
            get {
                object obj = ResourceManager.GetObject("toppng.com-blue-button-icon-icon-845x845", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap toppng1 {
            get {
                object obj = ResourceManager.GetObject("toppng1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
